// Définitions des 8 dimensions psychographiques (texte FR et image EN)
export const DIMENSIONS = [
  {
    key: "ambiguity",
    label: "Ambiguïté",
    default: 3,
    text: [
      ["clair", "précis", "défini"],
      ["doux", "nuancé", "suggestif"],
      ["voilé", "flou", "subtil"],
      ["flottant", "onirique", "vaporeux"],
      ["insaisissable", "surréaliste", "brumeux"],
    ],
    image: [
      ["sharp", "defined", "crisp"],
      ["soft", "gentle", "balanced"],
      ["hazy", "muted", "blurred"],
      ["dreamy", "misty", "ethereal"],
      ["surreal", "nebulous", "ghostly"],
    ],
  },
  {
    key: "emotion",
    label: "Intensité émotionnelle",
    default: 3,
    text: [
      ["neutre", "distant", "calme"],
      ["sensible", "délicat", "apaisant"],
      ["vibrant", "chaleureux", "vivant"],
      ["dramatique", "passionné", "poignant"],
      ["cathartique", "bouleversant", "enivrant"],
    ],
    image: [
      ["muted", "flat", "pale"],
      ["gentle", "soft", "subtle"],
      ["vivid", "bright", "warm"],
      ["intense", "rich", "deep"],
      ["explosive", "powerful", "striking"],
    ],
  },
  {
    key: "sensory",
    label: "Richesse sensorielle",
    default: 3,
    text: [
      ["simple", "épuré", "léger"],
      ["texturé", "discret", "fragile"],
      ["riche", "détaillé", "fluide"],
      ["immersif", "enveloppant", "profond"],
      ["saturé", "foisonnant", "englobant"],
    ],
    image: [
      ["flat", "plain", "clean"],
      ["subtle", "soft", "minimal"],
      ["layered", "detailed", "rich"],
      ["immersive", "deep", "vivid"],
      ["hyper-immersive", "lush", "dense"],
    ],
  },
  {
    key: "surprise",
    label: "Surprise",
    default: 3,
    text: [
      ["familier", "régulier", "attendu"],
      ["décalé", "curieux", "original"],
      ["surprenant", "inhabituel", "vibrant"],
      ["dérangeant", "troublant", "mystérieux"],
      ["déconcertant", "étrange", "déroutant"],
    ],
    image: [
      ["harmonious", "steady", "calm"],
      ["odd", "quirky", "unusual"],
      ["surprising", "vibrant", "unexpected"],
      ["unsettling", "eerie", "mysterious"],
      ["uncanny", "surreal", "disorienting"],
    ],
  },
  {
    key: "symbolic",
    label: "Profondeur symbolique",
    default: 3,
    text: [
      ["concret", "simple", "évident"],
      ["symbolique", "implicite", "poétique"],
      ["métaphorique", "subtil", "évocateur"],
      ["archétypal", "ancestral", "universel"],
      ["mythique", "intemporel", "sacré"],
    ],
    image: [
      ["literal", "plain", "simple"],
      ["symbolic", "subtle", "evocative"],
      ["poetic", "layered", "suggestive"],
      ["archetypal", "ancestral", "universal"],
      ["mythical", "timeless", "sacred"],
    ],
  },
  {
    key: "time",
    label: "Temporalité",
    default: 3,
    text: [
      ["actuel", "contemporain", "immédiat"],
      ["nostalgique", "doux", "flottant"],
      ["intemporel", "suspendu", "neutre"],
      ["cosmique", "infini", "spectral"],
      ["éternel", "hors du temps", "transcendant"],
    ],
    image: [
      ["modern", "present", "fresh"],
      ["vintage", "nostalgic", "soft"],
      ["timeless", "static", "balanced"],
      ["cosmic", "infinite", "spectral"],
      ["eternal", "ethereal", "transcendent"],
    ],
  },
  {
    key: "space",
    label: "Espace narratif",
    default: 3,
    text: [
      ["intime", "clos", "restreint"],
      ["enveloppant", "doux", "protecteur"],
      ["ouvert", "fluide", "aéré"],
      ["aérien", "large", "mouvant"],
      ["infini", "illimité", "expansif"],
    ],
    image: [
      ["close", "narrow", "tight"],
      ["soft", "wrapping", "cocooned"],
      ["open", "light", "airy"],
      ["wide", "flowing", "spacious"],
      ["boundless", "infinite", "vast"],
    ],
  },
  {
    key: "existential",
    label: "Résonance existentielle",
    default: 3,
    text: [
      ["quotidien", "simple", "familier"],
      ["introspectif", "personnel", "sensible"],
      ["profond", "contemplatif", "universel"],
      ["spirituel", "méditatif", "ouvert"],
      ["transcendant", "sacré", "infini"],
    ],
    image: [
      ["ordinary", "mundane", "simple"],
      ["reflective", "soft", "personal"],
      ["deep", "contemplative", "vast"],
      ["spiritual", "luminous", "meditative"],
      ["transcendent", "sacred", "infinite"],
    ],
  },
];